server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://8.130.17.7:3306/campus-window?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
  redis:
    url: redis://147258369@8.130.17.7:6379
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username: yuxin_798@163.com
    password: VRTADKMKPKSJJWCI
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
    protocol: smtp
    port: 465
  servlet:
    multipart:
      max-file-size: 1000MB
#logging:
#  config: classpath:logback-dev.xml
campus-window:
  minio:
    endpoint: http://8.130.17.7:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket: campus-bucket
    allowed-content-type:
      "[image/png]": png
      "[image/jpg]": jpg
      "[image/jpeg]": jpeg
      "[image/gif]": gif
      "[video/mp4]": mp4
#logging:
#  level:
#    web: trace


