server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://47.95.220.145:3306/Campus-Window?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 552010.a
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none

#  mail:
#    default-encoding: UTF-8
#    host: smtp.163.com
#    username: yuxin_798@163.com
#    password: VRTADKMKPKSJJWCI
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username: yuxin_798@163.com
    password: VRTADKMKPKSJJWCI
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
    protocol: smtp
    port: 465


